name: Auto Release

on:
  workflow_dispatch:
  push:
    paths:
      - 'build.gradle'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        if: runner.os == 'Windows'
      - name: Install WiX
        run: dotnet tool install --global wix
        if: runner.os == 'Windows'
#      - name: Build WiX on Windows
#        run: wix build .\nexus.wxs
#        if: runner.os == 'Windows'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Get version from build.gradle
        id: get_version
        run: |
          VERSION=$(grep '^version' build.gradle | cut -d '=' -f 2 | tr -d ' "')
          echo "::set-output name=VERSION::$VERSION"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build jlinkZip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/image.zip"
          commit: "master"
          tag: v${{ steps.get_version.outputs.VERSION }}